### ISSUE TITLE
Deeplinks stop working after disabling tracking

### ISSUE THREAD

**Issue by dbacic9** [BranchMetrics/ios-branch-deep-linking-attribution#1029]
Branch version: **"0.33.1"**
macOS: **10.15.4**
Xcode: **11.4.1 (11E503a)**

After calling **_Branch.setTrackingDisabled(true)_** any deeplink will stops working and 
**Branch.getInstance().initSession(launchOptions: launchOptions, andRegisterDeepLinkHandler: { params, error in })** receives error:

`Error Domain=io.branch.sdk.error Code=1015 "The Branch user session has not been initialized." UserInfo={NSLocalizedDescription=The Branch user session has not been initialized.}`

When enabling tracking **_Branch.setTrackingDisabled(false)_** the same links work.

Example links look like this:
_appname://page/contentid_

**Comment by echo-branch** [comment]
@dbacic9 
That error message is misleading due to a mistake on my part. I'll fix it in the next patch. The message should have been "User tracking is disabled."

When tracking is disabled nearly all communication with the Branch server is dropped. The only requests we allow are to resolve or create a link. The error just warns you that we're dropping a request to the Branch server.

Now why did we drop the request to resolve your link? The example link is not a Branch link, but rather a generic uri scheme. This will fail the Branch link check and you'll get the error message. For a Branch link, we'll go to the server to get the associated payload. This behavior is a little awkward IMO, cause in the normal case we at least return the link and say it's not a branch link. We should probably do the same here, I'll talk to my product team about improving this behavior. 

For now, I would just treat the error as a non-branch link report and handle the non-branch link yourself in openURL.

**Comment by echo-branch** [comment]
Error message has been corrected on staging.  Getting the same behavior for non-branch links when disabled is a more involved task that is backlogged.
