### ISSUE TITLE
advertisingIdentifier: reason for apple rejection.

### ISSUE THREAD

**Issue by pabloearg** [BranchMetrics/ios-branch-deep-linking-attribution#1049]
I'm using this version of the package:

`ios-branch-deep-linking-attribution-0.31.1
`

and Apple rejects our application with the following message:

> your Kids Category app collects IDFA information, which is not appropriate.

to test if our application is using IDFA in some plugin, we execute the following command in your code directly:

> fgrep -R advertisingIdentifier .

which retrieve this:

> Binary file ./Branch-TestBed-Swift/AdobeMobileLibrary/AdobeMobileLibrary_Watch.a matches
> Binary file ./Branch-TestBed-Swift/AdobeMobileLibrary/AdobeMobileLibrary_Extension.a matches
> Binary file ./Branch-TestBed-Swift/AdobeMobileLibrary/AdobeMobileLibrary_TV.a matches
> Binary file ./Branch-TestBed-Swift/AdobeMobileLibrary/AdobeMobileLibrary.a matches
> Binary file ./Branch.framework/Branch matches
> Binary file ./Branch.framework/Versions/A/Branch matches
> Binary file ./Branch.framework/Versions/Current/Branch matches
> ./Branch-SDK/Branch-SDK/BNCSystemObserver.m:        SEL advertisingIdentifierSelector = NSSelectorFromString(@"advertisingIdentifier");
> ./Branch-SDK/Branch-SDK/BNCSystemObserver.m:            ((NSUUID* (*)(id, SEL))[sharedManager methodForSelector:advertisingIdentifierSelector])
> ./Branch-SDK/Branch-SDK/BNCSystemObserver.m:                (sharedManager, advertisingIdentifierSelector);

![image](https://user-images.githubusercontent.com/29818262/90034004-7a1ac000-dc96-11ea-9192-a3503ec1d449.png)

apple are saying that:

> they want the app to contain absolutely no IDFA code, regardless of if it is called or not.

is there any way to remove all this?, i just hardcode the BNCSystemObserver.m code myself, but the other files i didnt know how to do it

on the other hand, for what i been researching, the "SafariServices" adds the AdSupport framework even if we dont do it in our project

**Comment by yoman07** [comment]
I have the same problem.  Any update on it?

**Comment by erisvaldojunior** [comment]
Is it fixed on branch sdk 0.35 ? I still can see the code on BNCSystemObserver.m by doing the grep thing.

**Comment by echo-branch** [comment]
It is fixed.  Issue was due to including AdSupport.framework by default when integrating with Cocoapods.  This is no longer the case in the 0.35.0 release.

That code does a check for AdSupport and only runs if it detects it.  If you feel uncomfortable with that, there is an optional compile time flag to completely remove that code, BRANCH_EXCLUDE_IDFA_CODE.  It should not be necessary since Apple does not reject apps for checking for libraries at run time.

**Comment by yoman07** [comment]
I used SDK 0.35 and I got rejected by Apple.  (After removing branch.io app has been approved)


`Guideline 1.3 - Safety - Kids Category


We noticed that your Kids Category app includes analytics, advertising and collects, transmits, or has the ability to share personal information or device information with third parties. 

Your app includes the following feature(s), contrary to guideline 1.3 of the App Store Review Guidelines:

Third-party analytics or third-party advertising with the ability to collect, transmit or share identifiable information, including, for example, IDFA. 

Next Steps

To resolve this issue, please remove this functionality or revise your app so that no personally identifiable information or device information is sent to third parties.`

**Comment by echo-branch** [comment]
@yoman07 
How are you integrating the Branch SDK?  Cocoapods, Carthage, Swift Package Manager?

Are you including AdSupport.framework when you add Branch?  Cause that framework is not allowed in children's apps.
