### ISSUE TITLE
Broken title when it is not alphabetical 

### ISSUE THREAD

**Issue by StevenArmandLee** [BranchMetrics/ios-branch-deep-linking-attribution#1161]
let buo = BranchUniversalObject.init(canonicalIdentifier: “”)
buo.title = “一”
buo.contentDescription = “description”

The above code will result in the shareSheet showing broken ascii

and subtitle doesn’t show the correct subtitle which is set in contentDescription

![053803C9-C719-4B07-BF5A-7B9D234A4D68](https://user-images.githubusercontent.com/9158731/141997933-99f57fc4-766d-44c9-b02a-0d6890eacefe.jpeg)

**Comment by JoanaDFerreira** [comment]
Same issue here

**Comment by echo-branch** [comment]
You'll need to set a placeholder url or LPLinkMetadata to control the look and feel of the sharesheet. In a future release, we will default it to your app's base url instead of the fallback bnc.lt url.

https://github.com/BranchMetrics/ios-branch-deep-linking-attribution/blob/master/Branch-SDK/BranchShareLink.h#L90-L96

**Comment by nsingh-branch** [comment]
The problem is the 一 symbol, which is unsupported. Using the - character instead will solve your issue.
