### ISSUE TITLE
Branch has been deprecated in favor of BranchSDK warning shown after pod install

### ISSUE THREAD

**Issue by vkundapur** [BranchMetrics/ios-branch-deep-linking-attribution#1232]
### Describe the bug

I am getting a warning `Branch has been deprecated in favor of BranchSDK` when I do a `pod install`

### Steps to reproduce

1. Add Branch React Native SDK v5.7.0 to your react native project
2. Navigate to iOS folder in the project
3. Run the command `pod Install`

### Expected behavior

No warning should be show as it's on the latest version

### SDK Version

5.7.0

### XCode Version

14.2

### Device

iPhone 14

### OS

16.2

**Comment by echo-branch** [comment]
This is by design. From Branch SDK 2.0 on, you'll need to use `BranchSDK` instead of `Branch`. This change is cause we renamed the framework umbrella header for better compatibility with Swift Package Manager. Note this impacts all import statements, but it should not impact any other setup for cocoapods users.

**Comment by vkundapur** [comment]
@echo-branch The documentation still says that we need to use Branch.
https://help.branch.io/developers-hub/docs/react-native

Should I follow the iOS SDK integration steps instead of react native?

**Comment by vkundapur** [comment]
Sorry, I think I've posted the bug on the wrong repo. I'll report it in `react-native` repo.
