### ISSUE TITLE
Installation Failed, Could not inspect the application package. 

### ISSUE THREAD

**Issue by tapannathvani** [BranchMetrics/ios-branch-deep-linking-attribution#958]
I Installed Branch through POD.     pod 'Branch'

After installing, when I run the project in device I am getting an error "Installation Failed, Could not inspect the application package".

I am using Xcode 10.2 with swift 5 language project.

**Comment by derrick-branch** [comment]
@tapannathvani can you write into support@branch.io to see whether they can help you? We are not aware of any issues that could be impacting this, so we suspect it is an integration issue rather than a bug on our end. Please include extensive steps to reproduce, as the above is not enough information to investigate.
